all: new-zealand-latest.osm.pbf

new-zealand-latest.osm.pbf:
	curl -LO https://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.pbf

clean:
	rm -f new-zealand-latest.osm.pbf

.PHONY: clean
